import unittest
from pprint import pformat
from random import randint
from types import GeneratorType

import numpy as np

from openmdao.api import IndepVarComp, Group, Problem
from openmdao.test.paraboloid import Paraboloid
from openmdao.test.sellar import SellarDerivatives, SellarStateConnection
from openmdao.test.simple_comps import SimpleArrayComp, ArrayComp2D
from openmdao.test.util import assert_rel_error

from openmdao.drivers.fullfactorial_driver import FullFactorialDriver

class TestFullFactorial(unittest.TestCase):
    def test_fullfactorial(self):
        prob = Problem()
        root = prob.root = Group()

        root.add('p1', IndepVarComp('x', 50.0), promotes=['*'])
        root.add('p2', IndepVarComp('y', 50.0), promotes=['*'])
        root.add('comp', Paraboloid(), promotes=['*'])

        prob.driver = FullFactorialDriver(2)
        prob.driver.add_desvar('x', low=0, high=1)
        prob.driver.add_desvar('y', low=0, high=1)
        prob.driver.add_objective('f_xy')
        runList = prob.driver._build_runlist()
        prob.setup(check=False)
        prob.run()
        # Assert that the runList generated is of Generator Type
        self.assertTrue((type(runList) == GeneratorType),"_build_runlist did not return a generator.")

        # assert that the cases generated by the driver are correct
        cases = list(runList)
        self.assertEqual([{'y' : 0.0, 'x' : 0.0},
                          {'y' : 0.0, 'x' : 1.0},
                          {'y' : 1.0, 'x' : 0.0},
                          {'y' : 1.0, 'x' : 1.0}],cases)


if __name__ == "__main__":
    unittest.main()

        